build: compile
	g++ main.o -o main.exe -L "..\lib" -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lsfml-network-s -lsfml-audio-s -lopengl32 -lfreetype -lwinmm -lgdi32 -mwindows
compile : 
	g++ -c main.cpp -I "..\include" -DSFML_STATIC

